(TeX-add-style-hook "sonk-revised"
 (lambda ()
    (LaTeX-add-bibliographies
     "bib-7293")
    (LaTeX-add-labels
     "Introduction"
     "ex:range"
     "ex:incomp"
     "DilationLearningAndEntropy"
     "dilation"
     "ex:dilation"
     "eq:d1"
     "eq:d2"
     "eq:d3"
     "ex:chocolates"
     "learning"
     "ex:learning"
     "entropy"
     "AugustinsConcessions"
     "jj1"
     "ex:die"
     "ex:rumour"
     "ex:urns"
     "jj2"
     "TheDoubleTask"
     "ex:aggreg"
     "ex:preccre"
     "eq:s2"
     "ex:king"
     "ex:monkey"
     "ex:threepris"
     "ex:linguist")
    (TeX-run-style-hooks
     "october"
     ""
     "latex2e"
     "art11"
     "article"
     "11pt")))

